### ISSUE TITLE
Fix code scanning alert - Inclusion of functionality from an untrusted source

### ISSUE THREAD

**Issue by imhunterand** [PrivatePwn0sec/PrivatePwn0sec#3]
Tracking issue for:
- [x] https://github.com/PrivatePwn0sec/PrivatePwn0sec/security/code-scanning/2

https://github.com/PrivatePwn0sec/PrivatePwn0sec/blob/bb9eec4c889942bbc5fdfca81a06d8247fe91b18/index.html#L609-L609

**Comment by sibermuda** [comment]
Fixed #1
